name: Build SmolSlimeConfigurator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            venv/Scripts/python -m pip install --upgrade pip
            venv/Scripts/python -m pip install pyinstaller customtkinter pyserial requests nrfuitl
          else
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install pyinstaller customtkinter pyserial requests nrfutil
          fi
        shell: bash

      - name: Build executable
        run: |
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            venv/Scripts/python -m PyInstaller --onefile --windowed --icon=icon.ico \
              --add-data "icon.ico;." \
              --add-binary "bin/nrfutil.exe;." \
              "./SmolSlimeConfiguratorV8-3-7.py"
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            source venv/bin/activate
            pyinstaller --onedir --windowed --icon=icon.icns \
              --add-binary "bin/nrfutil:." \
              "./SmolSlimeConfiguratorV8-3-7.py"
          else
            source venv/bin/activate
            pyinstaller --onefile --windowed --icon=icon.png \
              --add-data "icon.png:." \
              --add-binary "bin/nrfutil:." \
              "./SmolSlimeConfiguratorV8-3-7.py"
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SmolSlime-${{ matrix.os }}
          path: dist/*
