name: Build SmolSlimeConfigurator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies
      shell: bash
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter pyserial requests

    - name: Build executable with PyInstaller
      shell: bash
      run: |
        source venv/bin/activate

        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # Activate Windows venv (PowerShell)
          venv/Scripts/activate.ps1
          pyinstaller --onefile --windowed --icon=icon.ico \
            --add-data "icon.ico;." \
            --add-binary "venv/Scripts/nrfutil.exe;." \
            './SmolSlimeConfiguratorV8-3-7.py'

        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          pyinstaller --onedir --windowed --icon=icon.icns \
            --add-binary "venv/bin/nrfutil:." \
            './SmolSlimeConfiguratorV8-3-7.py'

        else
          # Linux
          pyinstaller --onefile --windowed --icon=icon.png \
            --add-data "icon.png:." \
            --add-binary "venv/bin/nrfutil:." \
            './SmolSlimeConfiguratorV8-3-7.py'
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SmolSlime-${{ matrix.os }}
        path: dist/*
